version: '3'

services:
  front:
    build:
      context: ./front
    container_name: labmine-front
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./front:/code
      - /code/node_modules
    environment:
      BASE_URL: http://api:8001
      BROWSER_BASE_URL: http://api:8001
    entrypoint: npm run dev

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: dbhost
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: 'Asia/Tokyo'

  api:
    build: ./api
    container_name: labmine-api
    restart: always
    volumes:
      - ./api/src:/code
      - static_volume:/static
    ports:
      - 8001:8001
    depends_on:
      - db
#    networks:
#      - default
#      - shared-network
  
  nginx:
      image: nginx:1.20.2
      container_name: labmine-nginx
      ports:
          - 80:80
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - static_volume:/static
        #- ./labmine-api/static:/static
      depends_on:
        - api

#networks:
#  shared-network:
#    external: true

volumes:
  static_volume:
