version: '3'

services:
  front:
    build:
      context: ./front
    container_name: labmine-front
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      BASE_URL: http://labmine-api:8001
      BROWSER_BASE_URL: http://labmine-api:8001

  db:
    image: mysql:5.7
    container_name: dbhost
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: 'Asia/Tokyo'

  api:
    build: ./api
    container_name: labmine-api
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db